[h2]External resource links[/h2]
[h3]Third-Party Themes[/h3]
[ul]
[*][url=https://github.com/omigeot/redstrap3]Redstrap[/url]
[*][url=https://bitbucket.org/tobiasd/red-clean]Clean[/url]
[*][url=https://github.com/tonybaldwin/redmatrixthemes/]nubasic[/url]
[*][url=https://github.com/deadsuperhero/redmatrix-themes]Sean Tilley's themes[/url]
[/ul]
[h3]Third-Party addons[/h3]
[ul]
[*][url=https://abcentric.net/git/abcjsplugin.git]ABCjs integration - display scores in posts (WIP)[/url]
[/ul]
[h3]Related projects[/h3]
[ul]
[*][url=https://addons.mozilla.org/en-US/firefox/addon/redshare/]Redshare for Firefox[/url]
[*][url=https://github.com/cvogeley/red-for-android]Red for Android[/url]
[*][url=https://github.com/zzottel/feed2red]feed2red.pl (posts Atom/RSS feeds to channel)[/url]
[*][url=https://wordpress.org/plugins/hubzilla-wp/]WordPress gateway (combine with wppost addon for full features)[/url]
[/ul]

#include doc/macros/main_footer.bb;
