#!/bin/bash -f

if [ $# -ne 2 ]; then
	echo usage: $0 repo_url nickname
	exit 1
fi

mkdir -p extend/widget/$2
mkdir widget > /dev/null 2>&1
git clone $1 extend/widget/$2
if [ $? -ne 0 ]; then
	exit $?
fi

filelist=(`ls extend/widget/$2`)


cd widget
for a in "${filelist[@]}" ; do
	base=`basename $a`
	if [ $base = '.git' ]; then
#		echo 'ignoring git'
		continue;
	fi
	if [ -x $base ]; then
#		echo $base 'file exists'
		continue;
	fi

	echo linking $base 

	ln -s ../extend/widget/$2/$base $base
done


