#!/bin/bash -f

if [ $# -lt 2 ]; then
	echo usage: $0 repo_url nickname
	exit 1
fi

#if [[ $1 != *"//github.com/redmatrix"* && $3 != 'insecure' ]]; then
#	echo "";
#	echo "This is NOT an official project repository.";
#	echo "In order to protect you from unverified and";
#	echo "possibly malicious content, this repository";
#	echo "will not be linked to your site unless you";
#	echo "append the word 'insecure' to the command.";
#	echo "";
#	exit 1
#fi

mkdir -p extend/addon/$2
mkdir addon > /dev/null 2>&1
git clone $1 extend/addon/$2
if [ $? -ne 0 ]; then
	exit $?
fi

filelist=(`ls extend/addon/$2`)

cd addon
for a in "${filelist[@]}" ; do
	base=`basename $a`
	if [ $base = '.git' ]; then
#		echo 'ignoring git'
		continue;
	fi
	if [ ! -d ../extend/addon/$2/$base ]; then
#		echo $a 'not a directory'
		continue;
	fi
	if [ -x $base ]; then
#		echo $base 'file exists'
		continue;
	fi

	echo linking $base 

	ln -s ../extend/addon/$2/$base $base
done


