#!/usr/bin/env php
<?php

require_once('include/cli_startup.php');

cli_startup();

require_once('include/help.php');

function update_docs_dir($s) {
	$f = basename($s);
	$d = dirname($s);
	if($s === 'doc/html')
		return;

	$files = glob("$d/$f");
	if($files) {
		foreach($files as $fi) {
			if($fi === 'doc/html')
				continue;
			echo $fi . "\n";
			if(is_dir($fi))
				update_docs_dir("$fi/*");
			else
				store_doc_file($fi);
		}
	}
}

update_docs_dir('doc/*');



