#!/bin/bash
if [ ! -d .git ]; then
	echo Unable to update `pwd`
	exit
fi
git pull

if [ -d extend ] ; then
	for a in  theme addon widget ; do
		if [ -d $a ]; then
			for b in  `ls extend/$a` ; do
				echo Updating $b
				'util/update_'$a'_repo' $b
			done
		fi
	done
fi
