#!/bin/bash -f

if [ $# -ne 1 ]; then
	echo usage: $0 repository
	echo "Repositories:"
	ls extend/widget
	exit 1
fi

cd extend/widget/$1

if [ -d .git ] ; then
	git pull
fi

cd ../../..

filelist=(`ls extend/widget/$1`)

cd widget

for a in "${filelist[@]}" ; do
	base=`basename $a`
	if [ $base = '.git' ]; then
#		echo 'ignoring git'
		continue;
	fi
	if [ -x $base ]; then
#		echo $base 'file exists'
		continue;
	fi

	echo linking $base 
	ln -s ../extend/widget/$1/$base $base
done
